// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/holdout/c04-103-annots-widgets",
  "cycle-04/holdout/c04-114-annots-widgets"
];

defineCycleParityShard({
  cycle: 4,
  phase: "holdout",
  shard: "annots-widgets",
  caseIds
});
