// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/holdout/c04-104-cmap-type3"
];

defineCycleParityShard({
  cycle: 4,
  phase: "holdout",
  shard: "cmap-type3",
  caseIds
});
