// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/holdout/c04-101-images-masks",
  "cycle-04/holdout/c04-112-images-masks"
];

defineCycleParityShard({
  cycle: 4,
  phase: "holdout",
  shard: "images-masks",
  caseIds
});
