// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/holdout/c04-108-table-grid",
  "cycle-04/holdout/c04-119-table-grid"
];

defineCycleParityShard({
  cycle: 4,
  phase: "holdout",
  shard: "table-grid",
  caseIds
});
