// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/holdout/c04-106-text-positioned",
  "cycle-04/holdout/c04-117-text-positioned"
];

defineCycleParityShard({
  cycle: 4,
  phase: "holdout",
  shard: "text-positioned",
  caseIds
});
