// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/holdout/c04-107-text-options",
  "cycle-04/holdout/c04-118-text-options"
];

defineCycleParityShard({
  cycle: 4,
  phase: "holdout",
  shard: "text-options",
  caseIds
});
