// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/holdout/c13-111-financial-report-boeing-2024-ar-p1",
  "cycle-13/holdout/c13-112-financial-report-boeing-2024-ar-p2",
  "cycle-13/holdout/c13-113-financial-report-boeing-2024-ar-p3",
  "cycle-13/holdout/c13-114-financial-report-boeing-2024-ar-p6",
  "cycle-13/holdout/c13-115-financial-report-boeing-2024-ar-p10",
  "cycle-13/holdout/c13-116-financial-report-boeing-2024-ar-p15",
  "cycle-13/holdout/c13-117-financial-report-boeing-2024-ar-p19",
  "cycle-13/holdout/c13-118-financial-report-boeing-2024-ar-p24",
  "cycle-13/holdout/c13-119-financial-report-boeing-2024-ar-p28",
  "cycle-13/holdout/c13-120-financial-report-boeing-2024-ar-p33"
];

defineCycleParityShard({
  cycle: 13,
  phase: "holdout",
  shard: "boeing-2024-ar",
  caseIds
});
