// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/holdout/c13-101-financial-report-federal-reserve-2024-ar-p62",
  "cycle-13/holdout/c13-102-financial-report-federal-reserve-2024-ar-p68",
  "cycle-13/holdout/c13-103-financial-report-federal-reserve-2024-ar-p74",
  "cycle-13/holdout/c13-104-financial-report-federal-reserve-2024-ar-p80",
  "cycle-13/holdout/c13-105-financial-report-federal-reserve-2024-ar-p86",
  "cycle-13/holdout/c13-106-financial-report-federal-reserve-2024-ar-p92",
  "cycle-13/holdout/c13-107-financial-report-federal-reserve-2024-ar-p98",
  "cycle-13/holdout/c13-108-financial-report-federal-reserve-2024-ar-p104",
  "cycle-13/holdout/c13-109-financial-report-federal-reserve-2024-ar-p111",
  "cycle-13/holdout/c13-110-financial-report-federal-reserve-2024-ar-p117"
];

defineCycleParityShard({
  cycle: 13,
  phase: "holdout",
  shard: "federal-reserve-2024-ar",
  caseIds
});
