// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/holdout/c12-113-scientific-technical-arxiv-pubtables-2110.00061-p1",
  "cycle-12/holdout/c12-114-scientific-technical-arxiv-pubtables-2110.00061-p2",
  "cycle-12/holdout/c12-115-scientific-technical-arxiv-pubtables-2110.00061-p3",
  "cycle-12/holdout/c12-116-scientific-technical-arxiv-pubtables-2110.00061-p4"
];

defineCycleParityShard({
  cycle: 12,
  phase: "holdout",
  shard: "arxiv-pubtables-2110-00061",
  caseIds
});
