// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/holdout/c12-101-financial-report-federal-reserve-2024-ar-p38",
  "cycle-12/holdout/c12-102-financial-report-federal-reserve-2024-ar-p44",
  "cycle-12/holdout/c12-103-financial-report-federal-reserve-2024-ar-p50",
  "cycle-12/holdout/c12-104-financial-report-federal-reserve-2024-ar-p56"
];

defineCycleParityShard({
  cycle: 12,
  phase: "holdout",
  shard: "federal-reserve-2024-ar",
  caseIds
});
