// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/holdout/c12-101-financial-report-govinfo-cfr12-2024-vol1-p1",
  "cycle-12/holdout/c12-102-financial-report-govinfo-cfr12-2024-vol1-p2",
  "cycle-12/holdout/c12-103-financial-report-govinfo-cfr12-2024-vol1-p3",
  "cycle-12/holdout/c12-104-financial-report-govinfo-cfr12-2024-vol1-p35",
  "cycle-12/holdout/c12-105-financial-report-govinfo-cfr12-2024-vol1-p69",
  "cycle-12/holdout/c12-106-financial-report-govinfo-cfr12-2024-vol1-p103",
  "cycle-12/holdout/c12-107-financial-report-govinfo-cfr12-2024-vol1-p137",
  "cycle-12/holdout/c12-108-financial-report-govinfo-cfr12-2024-vol1-p171",
  "cycle-12/holdout/c12-109-financial-report-govinfo-cfr12-2024-vol1-p205",
  "cycle-12/holdout/c12-110-financial-report-govinfo-cfr12-2024-vol1-p239"
];

defineCycleParityShard({
  cycle: 12,
  phase: "holdout",
  shard: "govinfo-cfr12-2024-vol1",
  caseIds
});
