// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/holdout/c12-111-financial-report-jpmorgan-2024-ar-p1",
  "cycle-12/holdout/c12-112-financial-report-jpmorgan-2024-ar-p2",
  "cycle-12/holdout/c12-113-financial-report-jpmorgan-2024-ar-p3",
  "cycle-12/holdout/c12-114-financial-report-jpmorgan-2024-ar-p12",
  "cycle-12/holdout/c12-115-financial-report-jpmorgan-2024-ar-p22",
  "cycle-12/holdout/c12-116-financial-report-jpmorgan-2024-ar-p33",
  "cycle-12/holdout/c12-117-financial-report-jpmorgan-2024-ar-p43",
  "cycle-12/holdout/c12-118-financial-report-jpmorgan-2024-ar-p54",
  "cycle-12/holdout/c12-119-financial-report-jpmorgan-2024-ar-p65",
  "cycle-12/holdout/c12-120-financial-report-jpmorgan-2024-ar-p75"
];

defineCycleParityShard({
  cycle: 12,
  phase: "holdout",
  shard: "jpmorgan-2024-ar",
  caseIds
});
