// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/holdout/c12-105-legal-regulatory-scotus-23-175-p16",
  "cycle-12/holdout/c12-106-legal-regulatory-scotus-23-175-p18",
  "cycle-12/holdout/c12-107-legal-regulatory-scotus-23-175-p20",
  "cycle-12/holdout/c12-108-legal-regulatory-scotus-23-175-p22"
];

defineCycleParityShard({
  cycle: 12,
  phase: "holdout",
  shard: "scotus-23-175",
  caseIds
});
