// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/holdout/c12-109-multilingual-text-un-a-64-95-zh-p5",
  "cycle-12/holdout/c12-110-multilingual-text-un-a-64-95-zh-p6",
  "cycle-12/holdout/c12-111-multilingual-text-un-a-64-95-zh-p7",
  "cycle-12/holdout/c12-112-multilingual-text-un-a-64-95-zh-p8"
];

defineCycleParityShard({
  cycle: 12,
  phase: "holdout",
  shard: "un-a-64-95-zh",
  caseIds
});
