// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/holdout/c12-120-text-geometry-uspto-patent-10000000-p1"
];

defineCycleParityShard({
  cycle: 12,
  phase: "holdout",
  shard: "uspto-patent-10000000",
  caseIds
});
