// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/holdout/c12-118-tagged-accessibility-verapdf-pdfua-table-pass-p1"
];

defineCycleParityShard({
  cycle: 12,
  phase: "holdout",
  shard: "verapdf-pdfua-table-pass",
  caseIds
});
