// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-004-annots-widgets",
  "cycle-04/working/c04-026-annots-widgets",
  "cycle-04/working/c04-037-annots-widgets",
  "cycle-04/working/c04-048-annots-widgets",
  "cycle-04/working/c04-059-annots-widgets",
  "cycle-04/working/c04-081-annots-widgets",
  "cycle-04/working/c04-092-annots-widgets"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "annots-widgets",
  caseIds
});
