// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-016-cmap-type3",
  "cycle-04/working/c04-027-cmap-type3",
  "cycle-04/working/c04-038-cmap-type3",
  "cycle-04/working/c04-049-cmap-type3",
  "cycle-04/working/c04-071-cmap-type3",
  "cycle-04/working/c04-082-cmap-type3",
  "cycle-04/working/c04-093-cmap-type3"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "cmap-type3",
  caseIds
});
