// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-003-forms-content",
  "cycle-04/working/c04-014-forms-content",
  "cycle-04/working/c04-036-forms-content",
  "cycle-04/working/c04-047-forms-content",
  "cycle-04/working/c04-058-forms-content",
  "cycle-04/working/c04-069-forms-content",
  "cycle-04/working/c04-091-forms-content"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "forms-content",
  caseIds
});
