// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-002-images-masks",
  "cycle-04/working/c04-013-images-masks",
  "cycle-04/working/c04-024-images-masks",
  "cycle-04/working/c04-046-images-masks",
  "cycle-04/working/c04-057-images-masks",
  "cycle-04/working/c04-068-images-masks",
  "cycle-04/working/c04-079-images-masks"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "images-masks",
  caseIds
});
