// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-006-marked-content",
  "cycle-04/working/c04-017-marked-content",
  "cycle-04/working/c04-028-marked-content",
  "cycle-04/working/c04-039-marked-content",
  "cycle-04/working/c04-061-marked-content",
  "cycle-04/working/c04-072-marked-content",
  "cycle-04/working/c04-083-marked-content",
  "cycle-04/working/c04-094-marked-content"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "marked-content",
  caseIds
});
