// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-011-page-boxes",
  "cycle-04/working/c04-022-page-boxes",
  "cycle-04/working/c04-033-page-boxes",
  "cycle-04/working/c04-044-page-boxes",
  "cycle-04/working/c04-066-page-boxes",
  "cycle-04/working/c04-077-page-boxes",
  "cycle-04/working/c04-088-page-boxes",
  "cycle-04/working/c04-099-page-boxes"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "page-boxes",
  caseIds
});
