// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-001-paths-colors",
  "cycle-04/working/c04-012-paths-colors",
  "cycle-04/working/c04-023-paths-colors",
  "cycle-04/working/c04-034-paths-colors",
  "cycle-04/working/c04-056-paths-colors",
  "cycle-04/working/c04-067-paths-colors",
  "cycle-04/working/c04-078-paths-colors",
  "cycle-04/working/c04-089-paths-colors"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "paths-colors",
  caseIds
});
