// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-005-real-tagged-pdf",
  "cycle-04/working/c04-030-real-tagged-pdf",
  "cycle-04/working/c04-065-real-tagged-pdf",
  "cycle-04/working/c04-095-real-tagged-pdf"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "real-tagged-pdf",
  caseIds
});
