// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-050-real-long-document",
  "cycle-04/working/c04-085-real-long-document"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "real-long-document",
  caseIds
});
