// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-010-real-images",
  "cycle-04/working/c04-100-real-images"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "real-images",
  caseIds
});
