// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-035-real-word-tolerance"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "real-word-tolerance",
  caseIds
});
