// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-021-table-text",
  "cycle-04/working/c04-032-table-text",
  "cycle-04/working/c04-043-table-text",
  "cycle-04/working/c04-054-table-text",
  "cycle-04/working/c04-076-table-text",
  "cycle-04/working/c04-087-table-text",
  "cycle-04/working/c04-098-table-text"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "table-text",
  caseIds
});
