// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-009-table-grid",
  "cycle-04/working/c04-031-table-grid",
  "cycle-04/working/c04-042-table-grid",
  "cycle-04/working/c04-053-table-grid",
  "cycle-04/working/c04-064-table-grid",
  "cycle-04/working/c04-086-table-grid",
  "cycle-04/working/c04-097-table-grid"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "table-grid",
  caseIds
});
