// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-008-text-options",
  "cycle-04/working/c04-019-text-options",
  "cycle-04/working/c04-041-text-options",
  "cycle-04/working/c04-052-text-options",
  "cycle-04/working/c04-063-text-options",
  "cycle-04/working/c04-074-text-options",
  "cycle-04/working/c04-096-text-options"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "text-options",
  caseIds
});
