// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-04/working/c04-007-text-positioned",
  "cycle-04/working/c04-018-text-positioned",
  "cycle-04/working/c04-029-text-positioned",
  "cycle-04/working/c04-051-text-positioned",
  "cycle-04/working/c04-062-text-positioned",
  "cycle-04/working/c04-073-text-positioned",
  "cycle-04/working/c04-084-text-positioned"
];

defineCycleParityShard({
  cycle: 4,
  phase: "working",
  shard: "text-positioned",
  caseIds
});
