// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-001-financial-report-apple-2024-10k-p97",
  "cycle-13/working/c13-002-financial-report-apple-2024-10k-p100",
  "cycle-13/working/c13-003-financial-report-apple-2024-10k-p104",
  "cycle-13/working/c13-004-financial-report-apple-2024-10k-p107",
  "cycle-13/working/c13-005-financial-report-apple-2024-10k-p111",
  "cycle-13/working/c13-006-financial-report-apple-2024-10k-p114",
  "cycle-13/working/c13-007-financial-report-apple-2024-10k-p118",
  "cycle-13/working/c13-008-financial-report-apple-2024-10k-p119",
  "cycle-13/working/c13-009-financial-report-apple-2024-10k-p120",
  "cycle-13/working/c13-010-financial-report-apple-2024-10k-p121"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "apple-2024-10k",
  caseIds
});
