// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-073-scientific-technical-arxiv-publaynet-1908.07836-p6",
  "cycle-13/working/c13-074-scientific-technical-arxiv-publaynet-1908.07836-p7",
  "cycle-13/working/c13-075-scientific-technical-arxiv-publaynet-1908.07836-p8"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "arxiv-publaynet-1908-07836",
  caseIds
});
