// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-076-scientific-technical-arxiv-pubtables-2110.00061-p5",
  "cycle-13/working/c13-077-scientific-technical-arxiv-pubtables-2110.00061-p6",
  "cycle-13/working/c13-078-scientific-technical-arxiv-pubtables-2110.00061-p7",
  "cycle-13/working/c13-079-scientific-technical-arxiv-pubtables-2110.00061-p8",
  "cycle-13/working/c13-080-scientific-technical-arxiv-pubtables-2110.00061-p9",
  "cycle-13/working/c13-081-scientific-technical-arxiv-pubtables-2110.00061-p10"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "arxiv-pubtables-2110-00061",
  caseIds
});
