// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-019-financial-report-berkshire-2024-ar-p44",
  "cycle-13/working/c13-020-financial-report-berkshire-2024-ar-p48",
  "cycle-13/working/c13-021-financial-report-berkshire-2024-ar-p52",
  "cycle-13/working/c13-022-financial-report-berkshire-2024-ar-p56",
  "cycle-13/working/c13-023-financial-report-berkshire-2024-ar-p61",
  "cycle-13/working/c13-024-financial-report-berkshire-2024-ar-p65",
  "cycle-13/working/c13-098-financial-report-berkshire-2024-ar-p69",
  "cycle-13/working/c13-099-financial-report-berkshire-2024-ar-p73",
  "cycle-13/working/c13-100-financial-report-berkshire-2024-ar-p78"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "berkshire-2024-ar",
  caseIds
});
