// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-011-financial-report-boj-semiannual-2024-jp-p73",
  "cycle-13/working/c13-012-financial-report-boj-semiannual-2024-jp-p76",
  "cycle-13/working/c13-013-financial-report-boj-semiannual-2024-jp-p78",
  "cycle-13/working/c13-014-financial-report-boj-semiannual-2024-jp-p81",
  "cycle-13/working/c13-015-financial-report-boj-semiannual-2024-jp-p83",
  "cycle-13/working/c13-016-financial-report-boj-semiannual-2024-jp-p86",
  "cycle-13/working/c13-017-financial-report-boj-semiannual-2024-jp-p87",
  "cycle-13/working/c13-018-financial-report-boj-semiannual-2024-jp-p88"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "boj-semiannual-2024-jp",
  caseIds
});
