// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-035-legal-regulatory-federal-register-2024-07-01-p319",
  "cycle-13/working/c13-036-legal-regulatory-federal-register-2024-07-01-p331",
  "cycle-13/working/c13-037-legal-regulatory-federal-register-2024-07-01-p342",
  "cycle-13/working/c13-038-legal-regulatory-federal-register-2024-07-01-p354",
  "cycle-13/working/c13-039-legal-regulatory-federal-register-2024-07-01-p365",
  "cycle-13/working/c13-040-legal-regulatory-federal-register-2024-07-01-p376",
  "cycle-13/working/c13-041-legal-regulatory-federal-register-2024-07-01-p388",
  "cycle-13/working/c13-042-legal-regulatory-federal-register-2024-07-01-p397",
  "cycle-13/working/c13-043-legal-regulatory-federal-register-2024-07-01-p398",
  "cycle-13/working/c13-044-legal-regulatory-federal-register-2024-07-01-p399"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "federal-register-2024-07-01",
  caseIds
});
