// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-025-legal-regulatory-federal-register-2024-01-02-p183",
  "cycle-13/working/c13-026-legal-regulatory-federal-register-2024-01-02-p190",
  "cycle-13/working/c13-027-legal-regulatory-federal-register-2024-01-02-p196",
  "cycle-13/working/c13-028-legal-regulatory-federal-register-2024-01-02-p203",
  "cycle-13/working/c13-029-legal-regulatory-federal-register-2024-01-02-p209",
  "cycle-13/working/c13-030-legal-regulatory-federal-register-2024-01-02-p216",
  "cycle-13/working/c13-031-legal-regulatory-federal-register-2024-01-02-p222",
  "cycle-13/working/c13-032-legal-regulatory-federal-register-2024-01-02-p227",
  "cycle-13/working/c13-033-legal-regulatory-federal-register-2024-01-02-p228",
  "cycle-13/working/c13-034-legal-regulatory-federal-register-2024-01-02-p229"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "federal-register-2024-01-02",
  caseIds
});
