// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-045-legal-regulatory-govinfo-hr815-enr-p32",
  "cycle-13/working/c13-046-legal-regulatory-govinfo-hr815-enr-p35",
  "cycle-13/working/c13-047-legal-regulatory-govinfo-hr815-enr-p38",
  "cycle-13/working/c13-048-legal-regulatory-govinfo-hr815-enr-p41"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "govinfo-hr815-enr",
  caseIds
});
