// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-092-upstream-regression-pdfjs-attachment-p1"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "pdfjs-attachment",
  caseIds
});
