// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-096-upstream-regression-pdfjs-truetype-without-cmap-p1"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "pdfjs-truetype-without-cmap",
  caseIds
});
