// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-093-upstream-regression-pdfjs-bad-page-labels-p1"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "pdfjs-bad-page-labels",
  caseIds
});
