// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-054-multilingual-text-un-a-64-95-en-p30",
  "cycle-13/working/c13-055-multilingual-text-un-a-64-95-en-p31"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "un-a-64-95-en",
  caseIds
});
