// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-056-multilingual-text-un-a-64-95-ru-p13",
  "cycle-13/working/c13-057-multilingual-text-un-a-64-95-ru-p14",
  "cycle-13/working/c13-058-multilingual-text-un-a-64-95-ru-p15",
  "cycle-13/working/c13-059-multilingual-text-un-a-64-95-ru-p16",
  "cycle-13/working/c13-060-multilingual-text-un-a-64-95-ru-p17",
  "cycle-13/working/c13-061-multilingual-text-un-a-64-95-ru-p18",
  "cycle-13/working/c13-062-multilingual-text-un-a-64-95-ru-p19",
  "cycle-13/working/c13-063-multilingual-text-un-a-64-95-ru-p20",
  "cycle-13/working/c13-064-multilingual-text-un-a-64-95-ru-p21",
  "cycle-13/working/c13-065-multilingual-text-un-a-64-95-ru-p22"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "un-a-64-95-ru",
  caseIds
});
