// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-066-multilingual-text-un-a-64-95-zh-p9",
  "cycle-13/working/c13-067-multilingual-text-un-a-64-95-zh-p10",
  "cycle-13/working/c13-068-multilingual-text-un-a-64-95-zh-p11",
  "cycle-13/working/c13-069-multilingual-text-un-a-64-95-zh-p12",
  "cycle-13/working/c13-070-multilingual-text-un-a-64-95-zh-p13",
  "cycle-13/working/c13-071-multilingual-text-un-a-64-95-zh-p14",
  "cycle-13/working/c13-072-multilingual-text-un-a-64-95-zh-p15"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "un-a-64-95-zh",
  caseIds
});
