// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-049-multilingual-text-un-a-64-95-ar-p31",
  "cycle-13/working/c13-050-multilingual-text-un-a-64-95-ar-p32",
  "cycle-13/working/c13-051-multilingual-text-un-a-64-95-ar-p33",
  "cycle-13/working/c13-052-multilingual-text-un-a-64-95-ar-p34",
  "cycle-13/working/c13-053-multilingual-text-un-a-64-95-ar-p35"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "un-a-64-95-ar",
  caseIds
});
