// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-13/working/c13-082-text-geometry-uspto-patent-10000000-p2",
  "cycle-13/working/c13-083-text-geometry-uspto-patent-10000000-p3",
  "cycle-13/working/c13-084-text-geometry-uspto-patent-10000000-p4",
  "cycle-13/working/c13-085-text-geometry-uspto-patent-10000000-p5",
  "cycle-13/working/c13-086-text-geometry-uspto-patent-10000000-p6",
  "cycle-13/working/c13-087-text-geometry-uspto-patent-10000000-p7",
  "cycle-13/working/c13-088-text-geometry-uspto-patent-10000000-p8",
  "cycle-13/working/c13-089-text-geometry-uspto-patent-10000000-p9",
  "cycle-13/working/c13-090-text-geometry-uspto-patent-10000000-p10",
  "cycle-13/working/c13-091-text-geometry-uspto-patent-10000000-p11"
];

defineCycleParityShard({
  cycle: 13,
  phase: "working",
  shard: "uspto-patent-10000000",
  caseIds
});
