// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/holdout/c14-104-financial-report-eba-2024-ar-p1",
  "cycle-14/holdout/c14-105-financial-report-eba-2024-ar-p2",
  "cycle-14/holdout/c14-106-financial-report-eba-2024-ar-p3",
  "cycle-14/holdout/c14-107-financial-report-eba-2024-ar-p5",
  "cycle-14/holdout/c14-108-financial-report-eba-2024-ar-p9",
  "cycle-14/holdout/c14-109-financial-report-eba-2024-ar-p13",
  "cycle-14/holdout/c14-110-financial-report-eba-2024-ar-p17",
  "cycle-14/holdout/c14-111-financial-report-eba-2024-ar-p21",
  "cycle-14/holdout/c14-112-financial-report-eba-2024-ar-p24",
  "cycle-14/holdout/c14-113-financial-report-eba-2024-ar-p28"
];

defineCycleParityShard({
  cycle: 14,
  phase: "holdout",
  shard: "eba-2024-ar",
  caseIds
});
