// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/holdout/c14-101-financial-report-eba-2024-summary-fr-p1",
  "cycle-14/holdout/c14-102-financial-report-eba-2024-summary-fr-p2",
  "cycle-14/holdout/c14-103-financial-report-eba-2024-summary-fr-p3"
];

defineCycleParityShard({
  cycle: 14,
  phase: "holdout",
  shard: "eba-2024-summary-fr",
  caseIds
});
