// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/holdout/c14-114-financial-report-fdic-2024-ar-p1",
  "cycle-14/holdout/c14-115-financial-report-fdic-2024-ar-p2",
  "cycle-14/holdout/c14-116-financial-report-fdic-2024-ar-p3",
  "cycle-14/holdout/c14-117-financial-report-fdic-2024-ar-p6",
  "cycle-14/holdout/c14-118-financial-report-fdic-2024-ar-p12",
  "cycle-14/holdout/c14-119-financial-report-fdic-2024-ar-p17",
  "cycle-14/holdout/c14-120-financial-report-fdic-2024-ar-p22"
];

defineCycleParityShard({
  cycle: 14,
  phase: "holdout",
  shard: "fdic-2024-ar",
  caseIds
});
