// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-107-annots-widgets",
  "cycle-06/holdout/c06-118-annots-widgets"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "annots-widgets",
  caseIds
});
