// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-108-cmap-type3",
  "cycle-06/holdout/c06-119-cmap-type3"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "cmap-type3",
  caseIds
});
