// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-106-forms-content",
  "cycle-06/holdout/c06-117-forms-content"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "forms-content",
  caseIds
});
