// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-116-images-masks"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "images-masks",
  caseIds
});
