// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-103-page-boxes",
  "cycle-06/holdout/c06-114-page-boxes"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "page-boxes",
  caseIds
});
