// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-110-real-images"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "real-images",
  caseIds
});
