// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-120-real-government-form"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "real-government-form",
  caseIds
});
