// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-101-table-grid",
  "cycle-06/holdout/c06-112-table-grid"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "table-grid",
  caseIds
});
