// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/holdout/c06-102-table-text",
  "cycle-06/holdout/c06-113-table-text"
];

defineCycleParityShard({
  cycle: 6,
  phase: "holdout",
  shard: "table-text",
  caseIds
});
