// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-008-annots-widgets",
  "cycle-06/working/c06-019-annots-widgets",
  "cycle-06/working/c06-041-annots-widgets",
  "cycle-06/working/c06-052-annots-widgets",
  "cycle-06/working/c06-063-annots-widgets",
  "cycle-06/working/c06-074-annots-widgets",
  "cycle-06/working/c06-096-annots-widgets"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "annots-widgets",
  caseIds
});
