// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-009-cmap-type3",
  "cycle-06/working/c06-031-cmap-type3",
  "cycle-06/working/c06-042-cmap-type3",
  "cycle-06/working/c06-053-cmap-type3",
  "cycle-06/working/c06-064-cmap-type3",
  "cycle-06/working/c06-086-cmap-type3",
  "cycle-06/working/c06-097-cmap-type3"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "cmap-type3",
  caseIds
});
