// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-007-forms-content",
  "cycle-06/working/c06-018-forms-content",
  "cycle-06/working/c06-029-forms-content",
  "cycle-06/working/c06-051-forms-content",
  "cycle-06/working/c06-062-forms-content",
  "cycle-06/working/c06-073-forms-content",
  "cycle-06/working/c06-084-forms-content"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "forms-content",
  caseIds
});
