// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-006-images-masks",
  "cycle-06/working/c06-017-images-masks",
  "cycle-06/working/c06-028-images-masks",
  "cycle-06/working/c06-039-images-masks",
  "cycle-06/working/c06-061-images-masks",
  "cycle-06/working/c06-072-images-masks",
  "cycle-06/working/c06-083-images-masks",
  "cycle-06/working/c06-094-images-masks"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "images-masks",
  caseIds
});
