// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-021-marked-content",
  "cycle-06/working/c06-032-marked-content",
  "cycle-06/working/c06-043-marked-content",
  "cycle-06/working/c06-054-marked-content",
  "cycle-06/working/c06-076-marked-content",
  "cycle-06/working/c06-087-marked-content",
  "cycle-06/working/c06-098-marked-content"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "marked-content",
  caseIds
});
