// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-004-page-boxes",
  "cycle-06/working/c06-026-page-boxes",
  "cycle-06/working/c06-037-page-boxes",
  "cycle-06/working/c06-048-page-boxes",
  "cycle-06/working/c06-059-page-boxes",
  "cycle-06/working/c06-081-page-boxes",
  "cycle-06/working/c06-092-page-boxes"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "page-boxes",
  caseIds
});
