// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-016-paths-colors",
  "cycle-06/working/c06-027-paths-colors",
  "cycle-06/working/c06-038-paths-colors",
  "cycle-06/working/c06-049-paths-colors",
  "cycle-06/working/c06-071-paths-colors",
  "cycle-06/working/c06-082-paths-colors",
  "cycle-06/working/c06-093-paths-colors"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "paths-colors",
  caseIds
});
