// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-005-real-long-document",
  "cycle-06/working/c06-060-real-long-document",
  "cycle-06/working/c06-095-real-long-document"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "real-long-document",
  caseIds
});
