// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-015-real-tagged-pdf",
  "cycle-06/working/c06-040-real-tagged-pdf",
  "cycle-06/working/c06-075-real-tagged-pdf"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "real-tagged-pdf",
  caseIds
});
