// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-085-real-financial-table"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "real-financial-table",
  caseIds
});
