// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-010-real-encrypted",
  "cycle-06/working/c06-100-real-encrypted"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "real-encrypted",
  caseIds
});
