// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-003-table-text",
  "cycle-06/working/c06-014-table-text",
  "cycle-06/working/c06-036-table-text",
  "cycle-06/working/c06-047-table-text",
  "cycle-06/working/c06-058-table-text",
  "cycle-06/working/c06-069-table-text",
  "cycle-06/working/c06-091-table-text"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "table-text",
  caseIds
});
