// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-002-table-grid",
  "cycle-06/working/c06-013-table-grid",
  "cycle-06/working/c06-024-table-grid",
  "cycle-06/working/c06-046-table-grid",
  "cycle-06/working/c06-057-table-grid",
  "cycle-06/working/c06-068-table-grid",
  "cycle-06/working/c06-079-table-grid"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "table-grid",
  caseIds
});
