// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-001-text-options",
  "cycle-06/working/c06-012-text-options",
  "cycle-06/working/c06-023-text-options",
  "cycle-06/working/c06-034-text-options",
  "cycle-06/working/c06-056-text-options",
  "cycle-06/working/c06-067-text-options",
  "cycle-06/working/c06-078-text-options",
  "cycle-06/working/c06-089-text-options"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "text-options",
  caseIds
});
