// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-06/working/c06-011-text-positioned",
  "cycle-06/working/c06-022-text-positioned",
  "cycle-06/working/c06-033-text-positioned",
  "cycle-06/working/c06-044-text-positioned",
  "cycle-06/working/c06-066-text-positioned",
  "cycle-06/working/c06-077-text-positioned",
  "cycle-06/working/c06-088-text-positioned",
  "cycle-06/working/c06-099-text-positioned"
];

defineCycleParityShard({
  cycle: 6,
  phase: "working",
  shard: "text-positioned",
  caseIds
});
