// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-001-financial-report-berkshire-2024-ar-p82",
  "cycle-14/working/c14-002-financial-report-berkshire-2024-ar-p86",
  "cycle-14/working/c14-003-financial-report-berkshire-2024-ar-p90",
  "cycle-14/working/c14-004-financial-report-berkshire-2024-ar-p95",
  "cycle-14/working/c14-005-financial-report-berkshire-2024-ar-p99",
  "cycle-14/working/c14-006-financial-report-berkshire-2024-ar-p103",
  "cycle-14/working/c14-007-financial-report-berkshire-2024-ar-p107",
  "cycle-14/working/c14-008-financial-report-berkshire-2024-ar-p112",
  "cycle-14/working/c14-009-financial-report-berkshire-2024-ar-p116",
  "cycle-14/working/c14-010-financial-report-berkshire-2024-ar-p120"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "berkshire-2024-ar",
  caseIds
});
