// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-021-financial-report-boeing-2024-ar-p38",
  "cycle-14/working/c14-022-financial-report-boeing-2024-ar-p42",
  "cycle-14/working/c14-023-financial-report-boeing-2024-ar-p47",
  "cycle-14/working/c14-024-financial-report-boeing-2024-ar-p51",
  "cycle-14/working/c14-072-financial-report-boeing-2024-ar-p56",
  "cycle-14/working/c14-073-financial-report-boeing-2024-ar-p60",
  "cycle-14/working/c14-074-financial-report-boeing-2024-ar-p65",
  "cycle-14/working/c14-075-financial-report-boeing-2024-ar-p70",
  "cycle-14/working/c14-076-financial-report-boeing-2024-ar-p74",
  "cycle-14/working/c14-077-financial-report-boeing-2024-ar-p79"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "boeing-2024-ar",
  caseIds
});
