// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-078-financial-report-caterpillar-2024-ar-p1",
  "cycle-14/working/c14-079-financial-report-caterpillar-2024-ar-p2",
  "cycle-14/working/c14-080-financial-report-caterpillar-2024-ar-p3",
  "cycle-14/working/c14-081-financial-report-caterpillar-2024-ar-p4",
  "cycle-14/working/c14-082-financial-report-caterpillar-2024-ar-p7",
  "cycle-14/working/c14-083-financial-report-caterpillar-2024-ar-p11",
  "cycle-14/working/c14-084-financial-report-caterpillar-2024-ar-p14",
  "cycle-14/working/c14-085-financial-report-caterpillar-2024-ar-p17",
  "cycle-14/working/c14-086-financial-report-caterpillar-2024-ar-p20",
  "cycle-14/working/c14-087-financial-report-caterpillar-2024-ar-p23"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "caterpillar-2024-ar",
  caseIds
});
