// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-088-financial-report-citigroup-2024-ar-p1",
  "cycle-14/working/c14-089-financial-report-citigroup-2024-ar-p2",
  "cycle-14/working/c14-090-financial-report-citigroup-2024-ar-p3",
  "cycle-14/working/c14-091-financial-report-citigroup-2024-ar-p11",
  "cycle-14/working/c14-092-financial-report-citigroup-2024-ar-p20",
  "cycle-14/working/c14-093-financial-report-citigroup-2024-ar-p30",
  "cycle-14/working/c14-094-financial-report-citigroup-2024-ar-p40",
  "cycle-14/working/c14-095-financial-report-citigroup-2024-ar-p50",
  "cycle-14/working/c14-096-financial-report-citigroup-2024-ar-p59",
  "cycle-14/working/c14-097-financial-report-citigroup-2024-ar-p69"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "citigroup-2024-ar",
  caseIds
});
