// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-098-financial-report-eba-2024-summary-de-p1",
  "cycle-14/working/c14-099-financial-report-eba-2024-summary-de-p2",
  "cycle-14/working/c14-100-financial-report-eba-2024-summary-de-p3"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "eba-2024-summary-de",
  caseIds
});
