// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-011-financial-report-federal-reserve-2024-ar-p123",
  "cycle-14/working/c14-012-financial-report-federal-reserve-2024-ar-p129",
  "cycle-14/working/c14-013-financial-report-federal-reserve-2024-ar-p135",
  "cycle-14/working/c14-014-financial-report-federal-reserve-2024-ar-p141",
  "cycle-14/working/c14-015-financial-report-federal-reserve-2024-ar-p147",
  "cycle-14/working/c14-016-financial-report-federal-reserve-2024-ar-p153",
  "cycle-14/working/c14-017-financial-report-federal-reserve-2024-ar-p159",
  "cycle-14/working/c14-018-financial-report-federal-reserve-2024-ar-p165",
  "cycle-14/working/c14-019-financial-report-federal-reserve-2024-ar-p171",
  "cycle-14/working/c14-020-financial-report-federal-reserve-2024-ar-p177"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "federal-reserve-2024-ar",
  caseIds
});
