// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-025-legal-regulatory-govinfo-hr815-enr-p45",
  "cycle-14/working/c14-026-legal-regulatory-govinfo-hr815-enr-p48",
  "cycle-14/working/c14-027-legal-regulatory-govinfo-hr815-enr-p51",
  "cycle-14/working/c14-028-legal-regulatory-govinfo-hr815-enr-p54",
  "cycle-14/working/c14-029-legal-regulatory-govinfo-hr815-enr-p57",
  "cycle-14/working/c14-030-legal-regulatory-govinfo-hr815-enr-p60",
  "cycle-14/working/c14-031-legal-regulatory-govinfo-hr815-enr-p63",
  "cycle-14/working/c14-032-legal-regulatory-govinfo-hr815-enr-p66",
  "cycle-14/working/c14-033-legal-regulatory-govinfo-hr815-enr-p70",
  "cycle-14/working/c14-034-legal-regulatory-govinfo-hr815-enr-p73"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "govinfo-hr815-enr",
  caseIds
});
