// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-045-legal-regulatory-scotus-23-939-p1",
  "cycle-14/working/c14-046-legal-regulatory-scotus-23-939-p2",
  "cycle-14/working/c14-047-legal-regulatory-scotus-23-939-p3",
  "cycle-14/working/c14-048-legal-regulatory-scotus-23-939-p4"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "scotus-23-939",
  caseIds
});
