// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-035-legal-regulatory-scotus-23-175-p24",
  "cycle-14/working/c14-036-legal-regulatory-scotus-23-175-p26",
  "cycle-14/working/c14-037-legal-regulatory-scotus-23-175-p28",
  "cycle-14/working/c14-038-legal-regulatory-scotus-23-175-p30",
  "cycle-14/working/c14-039-legal-regulatory-scotus-23-175-p32",
  "cycle-14/working/c14-040-legal-regulatory-scotus-23-175-p34",
  "cycle-14/working/c14-041-legal-regulatory-scotus-23-175-p36",
  "cycle-14/working/c14-042-legal-regulatory-scotus-23-175-p39",
  "cycle-14/working/c14-043-legal-regulatory-scotus-23-175-p41",
  "cycle-14/working/c14-044-legal-regulatory-scotus-23-175-p43"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "scotus-23-175",
  caseIds
});
