// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-049-multilingual-text-un-a-64-95-ru-p23",
  "cycle-14/working/c14-050-multilingual-text-un-a-64-95-ru-p24",
  "cycle-14/working/c14-051-multilingual-text-un-a-64-95-ru-p25",
  "cycle-14/working/c14-052-multilingual-text-un-a-64-95-ru-p26",
  "cycle-14/working/c14-053-multilingual-text-un-a-64-95-ru-p27",
  "cycle-14/working/c14-054-multilingual-text-un-a-64-95-ru-p28",
  "cycle-14/working/c14-055-multilingual-text-un-a-64-95-ru-p29",
  "cycle-14/working/c14-056-multilingual-text-un-a-64-95-ru-p30",
  "cycle-14/working/c14-057-multilingual-text-un-a-64-95-ru-p31",
  "cycle-14/working/c14-058-multilingual-text-un-a-64-95-ru-p32"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "un-a-64-95-ru",
  caseIds
});
