// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-059-multilingual-text-un-a-64-95-zh-p16",
  "cycle-14/working/c14-060-multilingual-text-un-a-64-95-zh-p17",
  "cycle-14/working/c14-061-multilingual-text-un-a-64-95-zh-p18",
  "cycle-14/working/c14-062-multilingual-text-un-a-64-95-zh-p19",
  "cycle-14/working/c14-063-multilingual-text-un-a-64-95-zh-p20",
  "cycle-14/working/c14-064-multilingual-text-un-a-64-95-zh-p21",
  "cycle-14/working/c14-065-multilingual-text-un-a-64-95-zh-p22",
  "cycle-14/working/c14-066-multilingual-text-un-a-64-95-zh-p23",
  "cycle-14/working/c14-067-multilingual-text-un-a-64-95-zh-p24",
  "cycle-14/working/c14-068-multilingual-text-un-a-64-95-zh-p25"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "un-a-64-95-zh",
  caseIds
});
