// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-070-text-geometry-uspto-patent-10000000-p12",
  "cycle-14/working/c14-071-text-geometry-uspto-patent-10000000-p13"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "uspto-patent-10000000",
  caseIds
});
