// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-14/working/c14-069-multilingual-text-verapdf-pdfua-unicode-cmap-pass-p1"
];

defineCycleParityShard({
  cycle: 14,
  phase: "working",
  shard: "verapdf-pdfua-unicode-cmap-pass",
  caseIds
});
