// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/holdout/c05-106-cmap-type3",
  "cycle-05/holdout/c05-117-cmap-type3"
];

defineCycleParityShard({
  cycle: 5,
  phase: "holdout",
  shard: "cmap-type3",
  caseIds
});
