// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/holdout/c05-103-images-masks",
  "cycle-05/holdout/c05-114-images-masks"
];

defineCycleParityShard({
  cycle: 5,
  phase: "holdout",
  shard: "images-masks",
  caseIds
});
