// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/holdout/c05-107-marked-content",
  "cycle-05/holdout/c05-118-marked-content"
];

defineCycleParityShard({
  cycle: 5,
  phase: "holdout",
  shard: "marked-content",
  caseIds
});
