// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/holdout/c05-101-page-boxes",
  "cycle-05/holdout/c05-112-page-boxes"
];

defineCycleParityShard({
  cycle: 5,
  phase: "holdout",
  shard: "page-boxes",
  caseIds
});
