// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/holdout/c05-102-paths-colors",
  "cycle-05/holdout/c05-113-paths-colors"
];

defineCycleParityShard({
  cycle: 5,
  phase: "holdout",
  shard: "paths-colors",
  caseIds
});
