// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/holdout/c05-110-real-dedupe"
];

defineCycleParityShard({
  cycle: 5,
  phase: "holdout",
  shard: "real-dedupe",
  caseIds
});
