// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/holdout/c05-109-text-options"
];

defineCycleParityShard({
  cycle: 5,
  phase: "holdout",
  shard: "text-options",
  caseIds
});
