// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/holdout/c05-108-text-positioned",
  "cycle-05/holdout/c05-119-text-positioned"
];

defineCycleParityShard({
  cycle: 5,
  phase: "holdout",
  shard: "text-positioned",
  caseIds
});
