// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-006-annots-widgets",
  "cycle-05/working/c05-017-annots-widgets",
  "cycle-05/working/c05-028-annots-widgets",
  "cycle-05/working/c05-039-annots-widgets",
  "cycle-05/working/c05-061-annots-widgets",
  "cycle-05/working/c05-072-annots-widgets",
  "cycle-05/working/c05-083-annots-widgets",
  "cycle-05/working/c05-094-annots-widgets"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "annots-widgets",
  caseIds
});
