// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-007-cmap-type3",
  "cycle-05/working/c05-018-cmap-type3",
  "cycle-05/working/c05-029-cmap-type3",
  "cycle-05/working/c05-051-cmap-type3",
  "cycle-05/working/c05-062-cmap-type3",
  "cycle-05/working/c05-073-cmap-type3",
  "cycle-05/working/c05-084-cmap-type3"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "cmap-type3",
  caseIds
});
