// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-016-forms-content",
  "cycle-05/working/c05-027-forms-content",
  "cycle-05/working/c05-038-forms-content",
  "cycle-05/working/c05-049-forms-content",
  "cycle-05/working/c05-071-forms-content",
  "cycle-05/working/c05-082-forms-content",
  "cycle-05/working/c05-093-forms-content"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "forms-content",
  caseIds
});
