// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-004-images-masks",
  "cycle-05/working/c05-026-images-masks",
  "cycle-05/working/c05-037-images-masks",
  "cycle-05/working/c05-048-images-masks",
  "cycle-05/working/c05-059-images-masks",
  "cycle-05/working/c05-081-images-masks",
  "cycle-05/working/c05-092-images-masks"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "images-masks",
  caseIds
});
