// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-008-marked-content",
  "cycle-05/working/c05-019-marked-content",
  "cycle-05/working/c05-041-marked-content",
  "cycle-05/working/c05-052-marked-content",
  "cycle-05/working/c05-063-marked-content",
  "cycle-05/working/c05-074-marked-content",
  "cycle-05/working/c05-096-marked-content"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "marked-content",
  caseIds
});
