// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-002-page-boxes",
  "cycle-05/working/c05-013-page-boxes",
  "cycle-05/working/c05-024-page-boxes",
  "cycle-05/working/c05-046-page-boxes",
  "cycle-05/working/c05-057-page-boxes",
  "cycle-05/working/c05-068-page-boxes",
  "cycle-05/working/c05-079-page-boxes"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "page-boxes",
  caseIds
});
