// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-003-paths-colors",
  "cycle-05/working/c05-014-paths-colors",
  "cycle-05/working/c05-036-paths-colors",
  "cycle-05/working/c05-047-paths-colors",
  "cycle-05/working/c05-058-paths-colors",
  "cycle-05/working/c05-069-paths-colors",
  "cycle-05/working/c05-091-paths-colors"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "paths-colors",
  caseIds
});
