// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-055-real-long-document",
  "cycle-05/working/c05-090-real-long-document"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "real-long-document",
  caseIds
});
