// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-040-real-word-tolerance"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "real-word-tolerance",
  caseIds
});
