// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-010-real-tagged-pdf",
  "cycle-05/working/c05-035-real-tagged-pdf",
  "cycle-05/working/c05-070-real-tagged-pdf",
  "cycle-05/working/c05-100-real-tagged-pdf"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "real-tagged-pdf",
  caseIds
});
