// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-011-table-grid",
  "cycle-05/working/c05-022-table-grid",
  "cycle-05/working/c05-033-table-grid",
  "cycle-05/working/c05-044-table-grid",
  "cycle-05/working/c05-066-table-grid",
  "cycle-05/working/c05-077-table-grid",
  "cycle-05/working/c05-088-table-grid",
  "cycle-05/working/c05-099-table-grid"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "table-grid",
  caseIds
});
