// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-001-table-text",
  "cycle-05/working/c05-012-table-text",
  "cycle-05/working/c05-023-table-text",
  "cycle-05/working/c05-034-table-text",
  "cycle-05/working/c05-056-table-text",
  "cycle-05/working/c05-067-table-text",
  "cycle-05/working/c05-078-table-text",
  "cycle-05/working/c05-089-table-text"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "table-text",
  caseIds
});
