// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-009-text-positioned",
  "cycle-05/working/c05-031-text-positioned",
  "cycle-05/working/c05-042-text-positioned",
  "cycle-05/working/c05-053-text-positioned",
  "cycle-05/working/c05-064-text-positioned",
  "cycle-05/working/c05-086-text-positioned",
  "cycle-05/working/c05-097-text-positioned"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "text-positioned",
  caseIds
});
