// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-05/working/c05-021-text-options",
  "cycle-05/working/c05-032-text-options",
  "cycle-05/working/c05-043-text-options",
  "cycle-05/working/c05-054-text-options",
  "cycle-05/working/c05-076-text-options",
  "cycle-05/working/c05-087-text-options",
  "cycle-05/working/c05-098-text-options"
];

defineCycleParityShard({
  cycle: 5,
  phase: "working",
  shard: "text-options",
  caseIds
});
