// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-001-financial-report-apple-2024-10k-p28",
  "cycle-11/working/c11-002-financial-report-apple-2024-10k-p32",
  "cycle-11/working/c11-003-financial-report-apple-2024-10k-p35",
  "cycle-11/working/c11-004-financial-report-apple-2024-10k-p39",
  "cycle-11/working/c11-005-financial-report-apple-2024-10k-p42",
  "cycle-11/working/c11-006-financial-report-apple-2024-10k-p46",
  "cycle-11/working/c11-007-financial-report-apple-2024-10k-p49",
  "cycle-11/working/c11-008-financial-report-apple-2024-10k-p52",
  "cycle-11/working/c11-009-financial-report-apple-2024-10k-p56",
  "cycle-11/working/c11-010-financial-report-apple-2024-10k-p59"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "apple-2024-10k",
  caseIds
});
