// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-097-scientific-technical-arxiv-attention-1706-03762-p4",
  "cycle-11/working/c11-098-scientific-technical-arxiv-attention-1706-03762-p5",
  "cycle-11/working/c11-099-scientific-technical-arxiv-attention-1706-03762-p6",
  "cycle-11/working/c11-100-scientific-technical-arxiv-attention-1706-03762-p7"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "arxiv-attention-1706-03762",
  caseIds
});
