// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-021-financial-report-berkshire-2024-ar-p10",
  "cycle-11/working/c11-022-financial-report-berkshire-2024-ar-p14",
  "cycle-11/working/c11-023-financial-report-berkshire-2024-ar-p18",
  "cycle-11/working/c11-024-financial-report-berkshire-2024-ar-p22"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "berkshire-2024-ar",
  caseIds
});
