// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-021-financial-report-boeing-2024-ar-p120",
  "cycle-11/working/c11-022-financial-report-boeing-2024-ar-p124",
  "cycle-11/working/c11-023-financial-report-boeing-2024-ar-p129",
  "cycle-11/working/c11-024-financial-report-boeing-2024-ar-p134",
  "cycle-11/working/c11-071-financial-report-boeing-2024-ar-p138",
  "cycle-11/working/c11-072-financial-report-boeing-2024-ar-p143",
  "cycle-11/working/c11-073-financial-report-boeing-2024-ar-p147",
  "cycle-11/working/c11-074-financial-report-boeing-2024-ar-p152",
  "cycle-11/working/c11-075-financial-report-boeing-2024-ar-p156",
  "cycle-11/working/c11-076-financial-report-boeing-2024-ar-p159"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "boeing-2024-ar",
  caseIds
});
