// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-011-financial-report-boj-semiannual-2024-jp-p23",
  "cycle-11/working/c11-012-financial-report-boj-semiannual-2024-jp-p26",
  "cycle-11/working/c11-013-financial-report-boj-semiannual-2024-jp-p28",
  "cycle-11/working/c11-014-financial-report-boj-semiannual-2024-jp-p31",
  "cycle-11/working/c11-015-financial-report-boj-semiannual-2024-jp-p33",
  "cycle-11/working/c11-016-financial-report-boj-semiannual-2024-jp-p36",
  "cycle-11/working/c11-017-financial-report-boj-semiannual-2024-jp-p38",
  "cycle-11/working/c11-018-financial-report-boj-semiannual-2024-jp-p41",
  "cycle-11/working/c11-019-financial-report-boj-semiannual-2024-jp-p43",
  "cycle-11/working/c11-020-financial-report-boj-semiannual-2024-jp-p46"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "boj-semiannual-2024-jp",
  caseIds
});
