// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-077-financial-report-caterpillar-2024-ar-p58",
  "cycle-11/working/c11-078-financial-report-caterpillar-2024-ar-p61",
  "cycle-11/working/c11-079-financial-report-caterpillar-2024-ar-p64",
  "cycle-11/working/c11-080-financial-report-caterpillar-2024-ar-p68",
  "cycle-11/working/c11-081-financial-report-caterpillar-2024-ar-p71",
  "cycle-11/working/c11-082-financial-report-caterpillar-2024-ar-p74",
  "cycle-11/working/c11-083-financial-report-caterpillar-2024-ar-p77",
  "cycle-11/working/c11-084-financial-report-caterpillar-2024-ar-p80",
  "cycle-11/working/c11-085-financial-report-caterpillar-2024-ar-p83",
  "cycle-11/working/c11-086-financial-report-caterpillar-2024-ar-p87"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "caterpillar-2024-ar",
  caseIds
});
