// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-087-financial-report-citigroup-2024-ar-p1",
  "cycle-11/working/c11-088-financial-report-citigroup-2024-ar-p2",
  "cycle-11/working/c11-089-financial-report-citigroup-2024-ar-p3",
  "cycle-11/working/c11-090-financial-report-citigroup-2024-ar-p11",
  "cycle-11/working/c11-091-financial-report-citigroup-2024-ar-p20",
  "cycle-11/working/c11-092-financial-report-citigroup-2024-ar-p30",
  "cycle-11/working/c11-093-financial-report-citigroup-2024-ar-p40",
  "cycle-11/working/c11-094-financial-report-citigroup-2024-ar-p50",
  "cycle-11/working/c11-095-financial-report-citigroup-2024-ar-p59",
  "cycle-11/working/c11-096-financial-report-citigroup-2024-ar-p69"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "citigroup-2024-ar",
  caseIds
});
