// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-025-forms-annotations-cms-1500-p3",
  "cycle-11/working/c11-026-forms-annotations-cms-1500-p4"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "cms-1500",
  caseIds
});
