// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-100-financial-report-eba-2024-summary-fr-p1"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "eba-2024-summary-fr",
  caseIds
});
