// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-097-financial-report-eba-2024-summary-de-p1",
  "cycle-11/working/c11-098-financial-report-eba-2024-summary-de-p2",
  "cycle-11/working/c11-099-financial-report-eba-2024-summary-de-p3"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "eba-2024-summary-de",
  caseIds
});
