// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-042-forms-annotations-fda-1572-p1",
  "cycle-11/working/c11-043-forms-annotations-fda-1572-p2",
  "cycle-11/working/c11-044-forms-annotations-fda-1572-p3",
  "cycle-11/working/c11-045-forms-annotations-fda-1572-p4",
  "cycle-11/working/c11-046-forms-annotations-fda-1572-p5",
  "cycle-11/working/c11-047-forms-annotations-fda-1572-p6",
  "cycle-11/working/c11-048-forms-annotations-fda-1572-p7"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "fda-1572",
  caseIds
});
