// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-059-legal-regulatory-federal-register-2024-07-01-p92",
  "cycle-11/working/c11-060-legal-regulatory-federal-register-2024-07-01-p103",
  "cycle-11/working/c11-061-legal-regulatory-federal-register-2024-07-01-p115",
  "cycle-11/working/c11-062-legal-regulatory-federal-register-2024-07-01-p126",
  "cycle-11/working/c11-063-legal-regulatory-federal-register-2024-07-01-p137",
  "cycle-11/working/c11-064-legal-regulatory-federal-register-2024-07-01-p149",
  "cycle-11/working/c11-065-legal-regulatory-federal-register-2024-07-01-p160",
  "cycle-11/working/c11-066-legal-regulatory-federal-register-2024-07-01-p172",
  "cycle-11/working/c11-067-legal-regulatory-federal-register-2024-07-01-p183",
  "cycle-11/working/c11-068-legal-regulatory-federal-register-2024-07-01-p194"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "federal-register-2024-07-01",
  caseIds
});
