// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-011-financial-report-federal-reserve-2024-ar-p92",
  "cycle-11/working/c11-012-financial-report-federal-reserve-2024-ar-p98",
  "cycle-11/working/c11-013-financial-report-federal-reserve-2024-ar-p104",
  "cycle-11/working/c11-014-financial-report-federal-reserve-2024-ar-p111",
  "cycle-11/working/c11-015-financial-report-federal-reserve-2024-ar-p117",
  "cycle-11/working/c11-016-financial-report-federal-reserve-2024-ar-p123",
  "cycle-11/working/c11-017-financial-report-federal-reserve-2024-ar-p129",
  "cycle-11/working/c11-018-financial-report-federal-reserve-2024-ar-p135",
  "cycle-11/working/c11-019-financial-report-federal-reserve-2024-ar-p141",
  "cycle-11/working/c11-020-financial-report-federal-reserve-2024-ar-p147"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "federal-reserve-2024-ar",
  caseIds
});
