// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-049-legal-regulatory-federal-register-2024-01-02-p53",
  "cycle-11/working/c11-050-legal-regulatory-federal-register-2024-01-02-p60",
  "cycle-11/working/c11-051-legal-regulatory-federal-register-2024-01-02-p66",
  "cycle-11/working/c11-052-legal-regulatory-federal-register-2024-01-02-p73",
  "cycle-11/working/c11-053-legal-regulatory-federal-register-2024-01-02-p79",
  "cycle-11/working/c11-054-legal-regulatory-federal-register-2024-01-02-p86",
  "cycle-11/working/c11-055-legal-regulatory-federal-register-2024-01-02-p92",
  "cycle-11/working/c11-056-legal-regulatory-federal-register-2024-01-02-p99",
  "cycle-11/working/c11-057-legal-regulatory-federal-register-2024-01-02-p105",
  "cycle-11/working/c11-058-legal-regulatory-federal-register-2024-01-02-p112"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "federal-register-2024-01-02",
  caseIds
});
