// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-069-legal-regulatory-govinfo-hr815-enr-p7",
  "cycle-11/working/c11-070-legal-regulatory-govinfo-hr815-enr-p10",
  "cycle-11/working/c11-071-legal-regulatory-govinfo-hr815-enr-p13",
  "cycle-11/working/c11-072-legal-regulatory-govinfo-hr815-enr-p17"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "govinfo-hr815-enr",
  caseIds
});
