// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-037-legal-regulatory-scotus-23-175-p16",
  "cycle-11/working/c11-038-legal-regulatory-scotus-23-175-p18",
  "cycle-11/working/c11-039-legal-regulatory-scotus-23-175-p20",
  "cycle-11/working/c11-040-legal-regulatory-scotus-23-175-p22",
  "cycle-11/working/c11-041-legal-regulatory-scotus-23-175-p24",
  "cycle-11/working/c11-042-legal-regulatory-scotus-23-175-p26",
  "cycle-11/working/c11-043-legal-regulatory-scotus-23-175-p28",
  "cycle-11/working/c11-044-legal-regulatory-scotus-23-175-p30",
  "cycle-11/working/c11-045-legal-regulatory-scotus-23-175-p32",
  "cycle-11/working/c11-046-legal-regulatory-scotus-23-175-p34"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "scotus-23-175",
  caseIds
});
