// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-027-forms-annotations-state-ds11-p2",
  "cycle-11/working/c11-028-forms-annotations-state-ds11-p3",
  "cycle-11/working/c11-029-forms-annotations-state-ds11-p4",
  "cycle-11/working/c11-030-forms-annotations-state-ds11-p5",
  "cycle-11/working/c11-031-forms-annotations-state-ds11-p6"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "state-ds11",
  caseIds
});
