// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-061-multilingual-text-un-a-64-95-zh-p7",
  "cycle-11/working/c11-062-multilingual-text-un-a-64-95-zh-p8",
  "cycle-11/working/c11-063-multilingual-text-un-a-64-95-zh-p9",
  "cycle-11/working/c11-064-multilingual-text-un-a-64-95-zh-p10",
  "cycle-11/working/c11-065-multilingual-text-un-a-64-95-zh-p11",
  "cycle-11/working/c11-066-multilingual-text-un-a-64-95-zh-p12",
  "cycle-11/working/c11-067-multilingual-text-un-a-64-95-zh-p13",
  "cycle-11/working/c11-068-multilingual-text-un-a-64-95-zh-p14",
  "cycle-11/working/c11-069-multilingual-text-un-a-64-95-zh-p15",
  "cycle-11/working/c11-070-multilingual-text-un-a-64-95-zh-p16"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "un-a-64-95-zh",
  caseIds
});
