// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-073-multilingual-text-un-a-64-95-ar-p11",
  "cycle-11/working/c11-074-multilingual-text-un-a-64-95-ar-p12",
  "cycle-11/working/c11-075-multilingual-text-un-a-64-95-ar-p13",
  "cycle-11/working/c11-076-multilingual-text-un-a-64-95-ar-p14",
  "cycle-11/working/c11-077-multilingual-text-un-a-64-95-ar-p15",
  "cycle-11/working/c11-078-multilingual-text-un-a-64-95-ar-p16",
  "cycle-11/working/c11-079-multilingual-text-un-a-64-95-ar-p17",
  "cycle-11/working/c11-080-multilingual-text-un-a-64-95-ar-p18",
  "cycle-11/working/c11-081-multilingual-text-un-a-64-95-ar-p19",
  "cycle-11/working/c11-082-multilingual-text-un-a-64-95-ar-p20"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "un-a-64-95-ar",
  caseIds
});
