// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-093-multilingual-text-un-a-64-95-ru-p5",
  "cycle-11/working/c11-094-multilingual-text-un-a-64-95-ru-p6",
  "cycle-11/working/c11-095-multilingual-text-un-a-64-95-ru-p7",
  "cycle-11/working/c11-096-multilingual-text-un-a-64-95-ru-p8"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "un-a-64-95-ru",
  caseIds
});
