// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-083-multilingual-text-un-a-64-95-en-p10",
  "cycle-11/working/c11-084-multilingual-text-un-a-64-95-en-p11",
  "cycle-11/working/c11-085-multilingual-text-un-a-64-95-en-p12",
  "cycle-11/working/c11-086-multilingual-text-un-a-64-95-en-p13",
  "cycle-11/working/c11-087-multilingual-text-un-a-64-95-en-p14",
  "cycle-11/working/c11-088-multilingual-text-un-a-64-95-en-p15",
  "cycle-11/working/c11-089-multilingual-text-un-a-64-95-en-p16",
  "cycle-11/working/c11-090-multilingual-text-un-a-64-95-en-p17",
  "cycle-11/working/c11-091-multilingual-text-un-a-64-95-en-p18",
  "cycle-11/working/c11-092-multilingual-text-un-a-64-95-en-p19"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "un-a-64-95-en",
  caseIds
});
