// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/working/c11-032-forms-annotations-va-21-526ez-p5",
  "cycle-11/working/c11-033-forms-annotations-va-21-526ez-p6",
  "cycle-11/working/c11-034-forms-annotations-va-21-526ez-p7",
  "cycle-11/working/c11-035-forms-annotations-va-21-526ez-p8",
  "cycle-11/working/c11-036-forms-annotations-va-21-526ez-p9",
  "cycle-11/working/c11-037-forms-annotations-va-21-526ez-p10",
  "cycle-11/working/c11-038-forms-annotations-va-21-526ez-p11",
  "cycle-11/working/c11-039-forms-annotations-va-21-526ez-p12",
  "cycle-11/working/c11-040-forms-annotations-va-21-526ez-p13",
  "cycle-11/working/c11-041-forms-annotations-va-21-526ez-p14"
];

defineCycleParityShard({
  cycle: 11,
  phase: "working",
  shard: "va-21-526ez",
  caseIds
});
