// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/holdout/c11-117-scientific-technical-arxiv-docling-2408-09869-p5",
  "cycle-11/holdout/c11-118-scientific-technical-arxiv-docling-2408-09869-p6",
  "cycle-11/holdout/c11-119-scientific-technical-arxiv-docling-2408-09869-p7",
  "cycle-11/holdout/c11-120-scientific-technical-arxiv-docling-2408-09869-p8"
];

defineCycleParityShard({
  cycle: 11,
  phase: "holdout",
  shard: "arxiv-docling-2408-09869",
  caseIds
});
