// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/holdout/c11-101-financial-report-eba-2024-ar-p1",
  "cycle-11/holdout/c11-102-financial-report-eba-2024-ar-p2",
  "cycle-11/holdout/c11-103-financial-report-eba-2024-ar-p3",
  "cycle-11/holdout/c11-104-financial-report-eba-2024-ar-p5",
  "cycle-11/holdout/c11-105-financial-report-eba-2024-ar-p9",
  "cycle-11/holdout/c11-106-financial-report-eba-2024-ar-p13",
  "cycle-11/holdout/c11-107-financial-report-eba-2024-ar-p17",
  "cycle-11/holdout/c11-108-financial-report-eba-2024-ar-p21",
  "cycle-11/holdout/c11-109-financial-report-eba-2024-ar-p24",
  "cycle-11/holdout/c11-110-financial-report-eba-2024-ar-p28"
];

defineCycleParityShard({
  cycle: 11,
  phase: "holdout",
  shard: "eba-2024-ar",
  caseIds
});
