// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/holdout/c11-111-financial-report-fdic-2024-ar-p1",
  "cycle-11/holdout/c11-112-financial-report-fdic-2024-ar-p2",
  "cycle-11/holdout/c11-113-financial-report-fdic-2024-ar-p3",
  "cycle-11/holdout/c11-114-financial-report-fdic-2024-ar-p6",
  "cycle-11/holdout/c11-115-financial-report-fdic-2024-ar-p12",
  "cycle-11/holdout/c11-116-financial-report-fdic-2024-ar-p17",
  "cycle-11/holdout/c11-117-financial-report-fdic-2024-ar-p22",
  "cycle-11/holdout/c11-118-financial-report-fdic-2024-ar-p27",
  "cycle-11/holdout/c11-119-financial-report-fdic-2024-ar-p33",
  "cycle-11/holdout/c11-120-financial-report-fdic-2024-ar-p38"
];

defineCycleParityShard({
  cycle: 11,
  phase: "holdout",
  shard: "fdic-2024-ar",
  caseIds
});
