// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/holdout/c11-101-financial-report-federal-reserve-2024-ar-p13",
  "cycle-11/holdout/c11-102-financial-report-federal-reserve-2024-ar-p19",
  "cycle-11/holdout/c11-103-financial-report-federal-reserve-2024-ar-p25",
  "cycle-11/holdout/c11-104-financial-report-federal-reserve-2024-ar-p31"
];

defineCycleParityShard({
  cycle: 11,
  phase: "holdout",
  shard: "federal-reserve-2024-ar",
  caseIds
});
