// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/holdout/c11-109-legal-regulatory-scotus-23-175-p7",
  "cycle-11/holdout/c11-110-legal-regulatory-scotus-23-175-p9",
  "cycle-11/holdout/c11-111-legal-regulatory-scotus-23-175-p11",
  "cycle-11/holdout/c11-112-legal-regulatory-scotus-23-175-p14"
];

defineCycleParityShard({
  cycle: 11,
  phase: "holdout",
  shard: "scotus-23-175",
  caseIds
});
