// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/holdout/c11-113-multilingual-text-un-a-64-95-zh-p1",
  "cycle-11/holdout/c11-114-multilingual-text-un-a-64-95-zh-p2",
  "cycle-11/holdout/c11-115-multilingual-text-un-a-64-95-zh-p3",
  "cycle-11/holdout/c11-116-multilingual-text-un-a-64-95-zh-p4"
];

defineCycleParityShard({
  cycle: 11,
  phase: "holdout",
  shard: "un-a-64-95-zh",
  caseIds
});
