// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/holdout/c11-108-forms-annotations-uspto-sb38-p1"
];

defineCycleParityShard({
  cycle: 11,
  phase: "holdout",
  shard: "uspto-sb38",
  caseIds
});
