// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-11/holdout/c11-105-forms-annotations-uspto-sb17-p1",
  "cycle-11/holdout/c11-106-forms-annotations-uspto-sb17-p2",
  "cycle-11/holdout/c11-107-forms-annotations-uspto-sb17-p3"
];

defineCycleParityShard({
  cycle: 11,
  phase: "holdout",
  shard: "uspto-sb17",
  caseIds
});
