// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-001-financial-report-apple-2024-10k-p63",
  "cycle-12/working/c12-002-financial-report-apple-2024-10k-p66",
  "cycle-12/working/c12-003-financial-report-apple-2024-10k-p70",
  "cycle-12/working/c12-004-financial-report-apple-2024-10k-p73",
  "cycle-12/working/c12-005-financial-report-apple-2024-10k-p76",
  "cycle-12/working/c12-006-financial-report-apple-2024-10k-p80",
  "cycle-12/working/c12-007-financial-report-apple-2024-10k-p83",
  "cycle-12/working/c12-008-financial-report-apple-2024-10k-p87",
  "cycle-12/working/c12-009-financial-report-apple-2024-10k-p90",
  "cycle-12/working/c12-010-financial-report-apple-2024-10k-p94"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "apple-2024-10k",
  caseIds
});
