// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-095-scientific-technical-arxiv-docling-2408-09869-p9"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "arxiv-docling-2408-09869",
  caseIds
});
