// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-096-scientific-technical-arxiv-publaynet-1908.07836-p1",
  "cycle-12/working/c12-097-scientific-technical-arxiv-publaynet-1908.07836-p2",
  "cycle-12/working/c12-098-scientific-technical-arxiv-publaynet-1908.07836-p3",
  "cycle-12/working/c12-099-scientific-technical-arxiv-publaynet-1908.07836-p4",
  "cycle-12/working/c12-100-scientific-technical-arxiv-publaynet-1908.07836-p5"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "arxiv-publaynet-1908-07836",
  caseIds
});
