// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-087-scientific-technical-arxiv-attention-1706-03762-p8",
  "cycle-12/working/c12-088-scientific-technical-arxiv-attention-1706-03762-p9",
  "cycle-12/working/c12-089-scientific-technical-arxiv-attention-1706-03762-p10",
  "cycle-12/working/c12-090-scientific-technical-arxiv-attention-1706-03762-p11",
  "cycle-12/working/c12-091-scientific-technical-arxiv-attention-1706-03762-p12",
  "cycle-12/working/c12-092-scientific-technical-arxiv-attention-1706-03762-p13",
  "cycle-12/working/c12-093-scientific-technical-arxiv-attention-1706-03762-p14",
  "cycle-12/working/c12-094-scientific-technical-arxiv-attention-1706-03762-p15"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "arxiv-attention-1706-03762",
  caseIds
});
