// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-021-financial-report-berkshire-2024-ar-p27",
  "cycle-12/working/c12-022-financial-report-berkshire-2024-ar-p31",
  "cycle-12/working/c12-023-financial-report-berkshire-2024-ar-p35",
  "cycle-12/working/c12-024-financial-report-berkshire-2024-ar-p39"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "berkshire-2024-ar",
  caseIds
});
