// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-021-financial-report-boeing-2024-ar-p160",
  "cycle-12/working/c12-022-financial-report-boeing-2024-ar-p161"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "boeing-2024-ar",
  caseIds
});
