// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-001-financial-report-boj-semiannual-2024-jp-p48",
  "cycle-12/working/c12-002-financial-report-boj-semiannual-2024-jp-p51",
  "cycle-12/working/c12-003-financial-report-boj-semiannual-2024-jp-p53",
  "cycle-12/working/c12-004-financial-report-boj-semiannual-2024-jp-p56",
  "cycle-12/working/c12-005-financial-report-boj-semiannual-2024-jp-p58",
  "cycle-12/working/c12-006-financial-report-boj-semiannual-2024-jp-p61",
  "cycle-12/working/c12-007-financial-report-boj-semiannual-2024-jp-p63",
  "cycle-12/working/c12-008-financial-report-boj-semiannual-2024-jp-p66",
  "cycle-12/working/c12-009-financial-report-boj-semiannual-2024-jp-p68",
  "cycle-12/working/c12-010-financial-report-boj-semiannual-2024-jp-p71"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "boj-semiannual-2024-jp",
  caseIds
});
