// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-023-financial-report-caterpillar-2024-ar-p90",
  "cycle-12/working/c12-024-financial-report-caterpillar-2024-ar-p93",
  "cycle-12/working/c12-069-financial-report-caterpillar-2024-ar-p96",
  "cycle-12/working/c12-070-financial-report-caterpillar-2024-ar-p99",
  "cycle-12/working/c12-071-financial-report-caterpillar-2024-ar-p102",
  "cycle-12/working/c12-072-financial-report-caterpillar-2024-ar-p106",
  "cycle-12/working/c12-073-financial-report-caterpillar-2024-ar-p109",
  "cycle-12/working/c12-074-financial-report-caterpillar-2024-ar-p110",
  "cycle-12/working/c12-075-financial-report-caterpillar-2024-ar-p111",
  "cycle-12/working/c12-076-financial-report-caterpillar-2024-ar-p112"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "caterpillar-2024-ar",
  caseIds
});
