// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-077-financial-report-citigroup-2024-ar-p79",
  "cycle-12/working/c12-078-financial-report-citigroup-2024-ar-p88",
  "cycle-12/working/c12-079-financial-report-citigroup-2024-ar-p98",
  "cycle-12/working/c12-080-financial-report-citigroup-2024-ar-p108",
  "cycle-12/working/c12-081-financial-report-citigroup-2024-ar-p118",
  "cycle-12/working/c12-082-financial-report-citigroup-2024-ar-p127",
  "cycle-12/working/c12-083-financial-report-citigroup-2024-ar-p137",
  "cycle-12/working/c12-084-financial-report-citigroup-2024-ar-p147",
  "cycle-12/working/c12-085-financial-report-citigroup-2024-ar-p156",
  "cycle-12/working/c12-086-financial-report-citigroup-2024-ar-p166"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "citigroup-2024-ar",
  caseIds
});
