// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-087-financial-report-eba-2024-summary-fr-p2",
  "cycle-12/working/c12-088-financial-report-eba-2024-summary-fr-p3"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "eba-2024-summary-fr",
  caseIds
});
