// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-089-financial-report-eba-2024-ar-p32",
  "cycle-12/working/c12-090-financial-report-eba-2024-ar-p36",
  "cycle-12/working/c12-091-financial-report-eba-2024-ar-p40",
  "cycle-12/working/c12-092-financial-report-eba-2024-ar-p44",
  "cycle-12/working/c12-093-financial-report-eba-2024-ar-p48",
  "cycle-12/working/c12-094-financial-report-eba-2024-ar-p52",
  "cycle-12/working/c12-095-financial-report-eba-2024-ar-p56",
  "cycle-12/working/c12-096-financial-report-eba-2024-ar-p60",
  "cycle-12/working/c12-097-financial-report-eba-2024-ar-p64",
  "cycle-12/working/c12-098-financial-report-eba-2024-ar-p68"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "eba-2024-ar",
  caseIds
});
