// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-026-forms-annotations-fda-1572-p8",
  "cycle-12/working/c12-027-forms-annotations-fda-1572-p9",
  "cycle-12/working/c12-028-forms-annotations-fda-1572-p10",
  "cycle-12/working/c12-029-forms-annotations-fda-1572-p11",
  "cycle-12/working/c12-030-forms-annotations-fda-1572-p12",
  "cycle-12/working/c12-031-forms-annotations-fda-1572-p13",
  "cycle-12/working/c12-032-forms-annotations-fda-1572-p14",
  "cycle-12/working/c12-033-forms-annotations-fda-1572-p15",
  "cycle-12/working/c12-034-forms-annotations-fda-1572-p16",
  "cycle-12/working/c12-035-forms-annotations-fda-1572-p17"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "fda-1572",
  caseIds
});
