// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-099-financial-report-fdic-2024-ar-p43",
  "cycle-12/working/c12-100-financial-report-fdic-2024-ar-p49"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "fdic-2024-ar",
  caseIds
});
