// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-049-legal-regulatory-federal-register-2024-07-01-p206",
  "cycle-12/working/c12-050-legal-regulatory-federal-register-2024-07-01-p217",
  "cycle-12/working/c12-051-legal-regulatory-federal-register-2024-07-01-p228",
  "cycle-12/working/c12-052-legal-regulatory-federal-register-2024-07-01-p240",
  "cycle-12/working/c12-053-legal-regulatory-federal-register-2024-07-01-p251",
  "cycle-12/working/c12-054-legal-regulatory-federal-register-2024-07-01-p263",
  "cycle-12/working/c12-055-legal-regulatory-federal-register-2024-07-01-p274",
  "cycle-12/working/c12-056-legal-regulatory-federal-register-2024-07-01-p285",
  "cycle-12/working/c12-057-legal-regulatory-federal-register-2024-07-01-p297",
  "cycle-12/working/c12-058-legal-regulatory-federal-register-2024-07-01-p308"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "federal-register-2024-07-01",
  caseIds
});
