// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-011-financial-report-federal-reserve-2024-ar-p153",
  "cycle-12/working/c12-012-financial-report-federal-reserve-2024-ar-p159",
  "cycle-12/working/c12-013-financial-report-federal-reserve-2024-ar-p165",
  "cycle-12/working/c12-014-financial-report-federal-reserve-2024-ar-p171",
  "cycle-12/working/c12-015-financial-report-federal-reserve-2024-ar-p177",
  "cycle-12/working/c12-016-financial-report-federal-reserve-2024-ar-p184",
  "cycle-12/working/c12-017-financial-report-federal-reserve-2024-ar-p190",
  "cycle-12/working/c12-018-financial-report-federal-reserve-2024-ar-p196",
  "cycle-12/working/c12-019-financial-report-federal-reserve-2024-ar-p202",
  "cycle-12/working/c12-020-financial-report-federal-reserve-2024-ar-p208"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "federal-reserve-2024-ar",
  caseIds
});
