// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-039-legal-regulatory-federal-register-2024-01-02-p118",
  "cycle-12/working/c12-040-legal-regulatory-federal-register-2024-01-02-p125",
  "cycle-12/working/c12-041-legal-regulatory-federal-register-2024-01-02-p131",
  "cycle-12/working/c12-042-legal-regulatory-federal-register-2024-01-02-p138",
  "cycle-12/working/c12-043-legal-regulatory-federal-register-2024-01-02-p144",
  "cycle-12/working/c12-044-legal-regulatory-federal-register-2024-01-02-p151",
  "cycle-12/working/c12-045-legal-regulatory-federal-register-2024-01-02-p157",
  "cycle-12/working/c12-046-legal-regulatory-federal-register-2024-01-02-p164",
  "cycle-12/working/c12-047-legal-regulatory-federal-register-2024-01-02-p170",
  "cycle-12/working/c12-048-legal-regulatory-federal-register-2024-01-02-p177"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "federal-register-2024-01-02",
  caseIds
});
