// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-059-legal-regulatory-govinfo-hr815-enr-p20",
  "cycle-12/working/c12-060-legal-regulatory-govinfo-hr815-enr-p23",
  "cycle-12/working/c12-061-legal-regulatory-govinfo-hr815-enr-p26",
  "cycle-12/working/c12-062-legal-regulatory-govinfo-hr815-enr-p29"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "govinfo-hr815-enr",
  caseIds
});
