// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-035-legal-regulatory-scotus-23-175-p36",
  "cycle-12/working/c12-036-legal-regulatory-scotus-23-175-p39",
  "cycle-12/working/c12-037-legal-regulatory-scotus-23-175-p41",
  "cycle-12/working/c12-038-legal-regulatory-scotus-23-175-p43",
  "cycle-12/working/c12-039-legal-regulatory-scotus-23-175-p45",
  "cycle-12/working/c12-040-legal-regulatory-scotus-23-175-p47",
  "cycle-12/working/c12-041-legal-regulatory-scotus-23-175-p49",
  "cycle-12/working/c12-042-legal-regulatory-scotus-23-175-p51",
  "cycle-12/working/c12-043-legal-regulatory-scotus-23-175-p53",
  "cycle-12/working/c12-044-legal-regulatory-scotus-23-175-p55"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "scotus-23-175",
  caseIds
});
