// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-045-legal-regulatory-scotus-23-939-p8",
  "cycle-12/working/c12-046-legal-regulatory-scotus-23-939-p11",
  "cycle-12/working/c12-047-legal-regulatory-scotus-23-939-p14",
  "cycle-12/working/c12-048-legal-regulatory-scotus-23-939-p18"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "scotus-23-939",
  caseIds
});
