// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-059-multilingual-text-un-a-64-95-zh-p17",
  "cycle-12/working/c12-060-multilingual-text-un-a-64-95-zh-p18",
  "cycle-12/working/c12-061-multilingual-text-un-a-64-95-zh-p19",
  "cycle-12/working/c12-062-multilingual-text-un-a-64-95-zh-p20",
  "cycle-12/working/c12-063-multilingual-text-un-a-64-95-zh-p21",
  "cycle-12/working/c12-064-multilingual-text-un-a-64-95-zh-p22",
  "cycle-12/working/c12-065-multilingual-text-un-a-64-95-zh-p23",
  "cycle-12/working/c12-066-multilingual-text-un-a-64-95-zh-p24",
  "cycle-12/working/c12-067-multilingual-text-un-a-64-95-zh-p25",
  "cycle-12/working/c12-068-multilingual-text-un-a-64-95-zh-p26"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "un-a-64-95-zh",
  caseIds
});
