// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-063-multilingual-text-un-a-64-95-ar-p21",
  "cycle-12/working/c12-064-multilingual-text-un-a-64-95-ar-p22",
  "cycle-12/working/c12-065-multilingual-text-un-a-64-95-ar-p23",
  "cycle-12/working/c12-066-multilingual-text-un-a-64-95-ar-p24",
  "cycle-12/working/c12-067-multilingual-text-un-a-64-95-ar-p25",
  "cycle-12/working/c12-068-multilingual-text-un-a-64-95-ar-p26",
  "cycle-12/working/c12-069-multilingual-text-un-a-64-95-ar-p27",
  "cycle-12/working/c12-070-multilingual-text-un-a-64-95-ar-p28",
  "cycle-12/working/c12-071-multilingual-text-un-a-64-95-ar-p29",
  "cycle-12/working/c12-072-multilingual-text-un-a-64-95-ar-p30"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "un-a-64-95-ar",
  caseIds
});
