// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-083-multilingual-text-un-a-64-95-ru-p9",
  "cycle-12/working/c12-084-multilingual-text-un-a-64-95-ru-p10",
  "cycle-12/working/c12-085-multilingual-text-un-a-64-95-ru-p11",
  "cycle-12/working/c12-086-multilingual-text-un-a-64-95-ru-p12"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "un-a-64-95-ru",
  caseIds
});
