// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-073-multilingual-text-un-a-64-95-en-p20",
  "cycle-12/working/c12-074-multilingual-text-un-a-64-95-en-p21",
  "cycle-12/working/c12-075-multilingual-text-un-a-64-95-en-p22",
  "cycle-12/working/c12-076-multilingual-text-un-a-64-95-en-p23",
  "cycle-12/working/c12-077-multilingual-text-un-a-64-95-en-p24",
  "cycle-12/working/c12-078-multilingual-text-un-a-64-95-en-p25",
  "cycle-12/working/c12-079-multilingual-text-un-a-64-95-en-p26",
  "cycle-12/working/c12-080-multilingual-text-un-a-64-95-en-p27",
  "cycle-12/working/c12-081-multilingual-text-un-a-64-95-en-p28",
  "cycle-12/working/c12-082-multilingual-text-un-a-64-95-en-p29"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "un-a-64-95-en",
  caseIds
});
