// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-036-forms-annotations-uspto-sb38-p2"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "uspto-sb38",
  caseIds
});
