// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-025-forms-annotations-va-21-526ez-p15"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "va-21-526ez",
  caseIds
});
