// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-12/working/c12-037-forms-annotations-verapdf-pdfua-forms-pass-p1"
];

defineCycleParityShard({
  cycle: 12,
  phase: "working",
  shard: "verapdf-pdfua-forms-pass",
  caseIds
});
