// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-001-financial-report-apple-2024-10k-p97",
  "cycle-10/working/c10-002-financial-report-apple-2024-10k-p100",
  "cycle-10/working/c10-003-financial-report-apple-2024-10k-p104",
  "cycle-10/working/c10-004-financial-report-apple-2024-10k-p107",
  "cycle-10/working/c10-005-financial-report-apple-2024-10k-p111",
  "cycle-10/working/c10-006-financial-report-apple-2024-10k-p114",
  "cycle-10/working/c10-007-financial-report-apple-2024-10k-p118",
  "cycle-10/working/c10-008-financial-report-apple-2024-10k-p119",
  "cycle-10/working/c10-009-financial-report-apple-2024-10k-p120",
  "cycle-10/working/c10-010-financial-report-apple-2024-10k-p121"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "apple-2024-10k",
  caseIds
});
