// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-098-scientific-technical-arxiv-attention-1706-03762-p1",
  "cycle-10/working/c10-099-scientific-technical-arxiv-attention-1706-03762-p2",
  "cycle-10/working/c10-100-scientific-technical-arxiv-attention-1706-03762-p3"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "arxiv-attention-1706-03762",
  caseIds
});
