// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-021-financial-report-berkshire-2024-ar-p120",
  "cycle-10/working/c10-022-financial-report-berkshire-2024-ar-p124",
  "cycle-10/working/c10-023-financial-report-berkshire-2024-ar-p129",
  "cycle-10/working/c10-024-financial-report-berkshire-2024-ar-p133",
  "cycle-10/working/c10-090-financial-report-berkshire-2024-ar-p137",
  "cycle-10/working/c10-091-financial-report-berkshire-2024-ar-p141",
  "cycle-10/working/c10-092-financial-report-berkshire-2024-ar-p146",
  "cycle-10/working/c10-093-financial-report-berkshire-2024-ar-p148",
  "cycle-10/working/c10-094-financial-report-berkshire-2024-ar-p149",
  "cycle-10/working/c10-095-financial-report-berkshire-2024-ar-p150"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "berkshire-2024-ar",
  caseIds
});
