// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-021-financial-report-berkshire-2024-ar-p1",
  "cycle-10/working/c10-022-financial-report-berkshire-2024-ar-p2",
  "cycle-10/working/c10-023-financial-report-berkshire-2024-ar-p3",
  "cycle-10/working/c10-024-financial-report-berkshire-2024-ar-p5"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "berkshire-2024-ar",
  caseIds
});
