// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-011-financial-report-boj-semiannual-2024-jp-p1",
  "cycle-10/working/c10-012-financial-report-boj-semiannual-2024-jp-p2",
  "cycle-10/working/c10-013-financial-report-boj-semiannual-2024-jp-p3",
  "cycle-10/working/c10-014-financial-report-boj-semiannual-2024-jp-p6",
  "cycle-10/working/c10-015-financial-report-boj-semiannual-2024-jp-p8",
  "cycle-10/working/c10-016-financial-report-boj-semiannual-2024-jp-p11",
  "cycle-10/working/c10-017-financial-report-boj-semiannual-2024-jp-p13",
  "cycle-10/working/c10-018-financial-report-boj-semiannual-2024-jp-p16",
  "cycle-10/working/c10-019-financial-report-boj-semiannual-2024-jp-p18",
  "cycle-10/working/c10-020-financial-report-boj-semiannual-2024-jp-p21"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "boj-semiannual-2024-jp",
  caseIds
});
