// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-025-forms-annotations-cms-1500-p1",
  "cycle-10/working/c10-026-forms-annotations-cms-1500-p2"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "cms-1500",
  caseIds
});
