// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-027-forms-annotations-dol-wh-380-e-p1",
  "cycle-10/working/c10-028-forms-annotations-dol-wh-380-e-p2",
  "cycle-10/working/c10-029-forms-annotations-dol-wh-380-e-p3",
  "cycle-10/working/c10-030-forms-annotations-dol-wh-380-e-p4"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "dol-wh-380-e",
  caseIds
});
