// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-096-financial-report-federal-reserve-2024-ar-p62",
  "cycle-10/working/c10-097-financial-report-federal-reserve-2024-ar-p68",
  "cycle-10/working/c10-098-financial-report-federal-reserve-2024-ar-p74",
  "cycle-10/working/c10-099-financial-report-federal-reserve-2024-ar-p80",
  "cycle-10/working/c10-100-financial-report-federal-reserve-2024-ar-p86"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "federal-reserve-2024-ar",
  caseIds
});
