// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-050-legal-regulatory-federal-register-2024-01-02-p1",
  "cycle-10/working/c10-051-legal-regulatory-federal-register-2024-01-02-p2",
  "cycle-10/working/c10-052-legal-regulatory-federal-register-2024-01-02-p3",
  "cycle-10/working/c10-053-legal-regulatory-federal-register-2024-01-02-p8",
  "cycle-10/working/c10-054-legal-regulatory-federal-register-2024-01-02-p14",
  "cycle-10/working/c10-055-legal-regulatory-federal-register-2024-01-02-p21",
  "cycle-10/working/c10-056-legal-regulatory-federal-register-2024-01-02-p27",
  "cycle-10/working/c10-057-legal-regulatory-federal-register-2024-01-02-p34",
  "cycle-10/working/c10-058-legal-regulatory-federal-register-2024-01-02-p40",
  "cycle-10/working/c10-059-legal-regulatory-federal-register-2024-01-02-p47"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "federal-register-2024-01-02",
  caseIds
});
