// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-047-legal-regulatory-federal-register-2024-07-01-p319",
  "cycle-10/working/c10-048-legal-regulatory-federal-register-2024-07-01-p331",
  "cycle-10/working/c10-049-legal-regulatory-federal-register-2024-07-01-p342",
  "cycle-10/working/c10-050-legal-regulatory-federal-register-2024-07-01-p354",
  "cycle-10/working/c10-051-legal-regulatory-federal-register-2024-07-01-p365",
  "cycle-10/working/c10-052-legal-regulatory-federal-register-2024-07-01-p376",
  "cycle-10/working/c10-053-legal-regulatory-federal-register-2024-07-01-p388",
  "cycle-10/working/c10-054-legal-regulatory-federal-register-2024-07-01-p397",
  "cycle-10/working/c10-055-legal-regulatory-federal-register-2024-07-01-p398",
  "cycle-10/working/c10-056-legal-regulatory-federal-register-2024-07-01-p399"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "federal-register-2024-07-01",
  caseIds
});
