// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-037-legal-regulatory-federal-register-2024-01-02-p183",
  "cycle-10/working/c10-038-legal-regulatory-federal-register-2024-01-02-p190",
  "cycle-10/working/c10-039-legal-regulatory-federal-register-2024-01-02-p196",
  "cycle-10/working/c10-040-legal-regulatory-federal-register-2024-01-02-p203",
  "cycle-10/working/c10-041-legal-regulatory-federal-register-2024-01-02-p209",
  "cycle-10/working/c10-042-legal-regulatory-federal-register-2024-01-02-p216",
  "cycle-10/working/c10-043-legal-regulatory-federal-register-2024-01-02-p222",
  "cycle-10/working/c10-044-legal-regulatory-federal-register-2024-01-02-p227",
  "cycle-10/working/c10-045-legal-regulatory-federal-register-2024-01-02-p228",
  "cycle-10/working/c10-046-legal-regulatory-federal-register-2024-01-02-p229"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "federal-register-2024-01-02",
  caseIds
});
