// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-060-legal-regulatory-federal-register-2024-07-01-p1",
  "cycle-10/working/c10-061-legal-regulatory-federal-register-2024-07-01-p2",
  "cycle-10/working/c10-062-legal-regulatory-federal-register-2024-07-01-p3",
  "cycle-10/working/c10-063-legal-regulatory-federal-register-2024-07-01-p12",
  "cycle-10/working/c10-064-legal-regulatory-federal-register-2024-07-01-p24",
  "cycle-10/working/c10-065-legal-regulatory-federal-register-2024-07-01-p35",
  "cycle-10/working/c10-066-legal-regulatory-federal-register-2024-07-01-p46",
  "cycle-10/working/c10-067-legal-regulatory-federal-register-2024-07-01-p58",
  "cycle-10/working/c10-068-legal-regulatory-federal-register-2024-07-01-p69",
  "cycle-10/working/c10-069-legal-regulatory-federal-register-2024-07-01-p81"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "federal-register-2024-07-01",
  caseIds
});
