// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-070-legal-regulatory-govinfo-hr815-enr-p1",
  "cycle-10/working/c10-071-legal-regulatory-govinfo-hr815-enr-p2",
  "cycle-10/working/c10-072-legal-regulatory-govinfo-hr815-enr-p3",
  "cycle-10/working/c10-073-legal-regulatory-govinfo-hr815-enr-p4"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "govinfo-hr815-enr",
  caseIds
});
