// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-057-legal-regulatory-govinfo-hr815-enr-p32",
  "cycle-10/working/c10-058-legal-regulatory-govinfo-hr815-enr-p35",
  "cycle-10/working/c10-059-legal-regulatory-govinfo-hr815-enr-p38",
  "cycle-10/working/c10-060-legal-regulatory-govinfo-hr815-enr-p41"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "govinfo-hr815-enr",
  caseIds
});
