// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-032-forms-annotations-irs-fw4-p1",
  "cycle-10/working/c10-033-forms-annotations-irs-fw4-p2",
  "cycle-10/working/c10-034-forms-annotations-irs-fw4-p3",
  "cycle-10/working/c10-035-forms-annotations-irs-fw4-p4",
  "cycle-10/working/c10-036-forms-annotations-irs-fw4-p5"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "irs-fw4",
  caseIds
});
