// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-027-forms-annotations-irs-f1040-p1",
  "cycle-10/working/c10-028-forms-annotations-irs-f1040-p2"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "irs-f1040",
  caseIds
});
