// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-029-forms-annotations-irs-f941-p1",
  "cycle-10/working/c10-030-forms-annotations-irs-f941-p2",
  "cycle-10/working/c10-031-forms-annotations-irs-f941-p3"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "irs-f941",
  caseIds
});
