// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-075-multilingual-text-pdfjs-identity-to-unicode-map-p1"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "pdfjs-identity-to-unicode-map",
  caseIds
});
