// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-087-upstream-regression-pdfjs-issue6068-p1"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "pdfjs-issue6068",
  caseIds
});
