// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-043-forms-annotations-pdfjs-annotation-text-widget-p1"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "pdfjs-annotation-text-widget",
  caseIds
});
