// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-089-upstream-regression-pdfjs-type3-word-spacing-p1"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "pdfjs-type3-word-spacing",
  caseIds
});
