// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-069-multilingual-text-un-a-64-95-ru-p1",
  "cycle-10/working/c10-070-multilingual-text-un-a-64-95-ru-p2",
  "cycle-10/working/c10-071-multilingual-text-un-a-64-95-ru-p3",
  "cycle-10/working/c10-072-multilingual-text-un-a-64-95-ru-p4",
  "cycle-10/working/c10-073-multilingual-text-un-a-64-95-ru-p5",
  "cycle-10/working/c10-074-multilingual-text-un-a-64-95-ru-p6",
  "cycle-10/working/c10-075-multilingual-text-un-a-64-95-ru-p7",
  "cycle-10/working/c10-076-multilingual-text-un-a-64-95-ru-p8",
  "cycle-10/working/c10-077-multilingual-text-un-a-64-95-ru-p9",
  "cycle-10/working/c10-078-multilingual-text-un-a-64-95-ru-p10"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "un-a-64-95-ru",
  caseIds
});
