// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-068-multilingual-text-un-a-64-95-en-p31"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "un-a-64-95-en",
  caseIds
});
