// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-079-multilingual-text-un-a-64-95-ar-p1",
  "cycle-10/working/c10-080-multilingual-text-un-a-64-95-ar-p2",
  "cycle-10/working/c10-081-multilingual-text-un-a-64-95-ar-p3",
  "cycle-10/working/c10-082-multilingual-text-un-a-64-95-ar-p4",
  "cycle-10/working/c10-083-multilingual-text-un-a-64-95-ar-p5",
  "cycle-10/working/c10-084-multilingual-text-un-a-64-95-ar-p6",
  "cycle-10/working/c10-085-multilingual-text-un-a-64-95-ar-p7",
  "cycle-10/working/c10-086-multilingual-text-un-a-64-95-ar-p8",
  "cycle-10/working/c10-087-multilingual-text-un-a-64-95-ar-p9",
  "cycle-10/working/c10-088-multilingual-text-un-a-64-95-ar-p10"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "un-a-64-95-ar",
  caseIds
});
