// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-063-multilingual-text-un-a-64-95-ar-p31",
  "cycle-10/working/c10-064-multilingual-text-un-a-64-95-ar-p32",
  "cycle-10/working/c10-065-multilingual-text-un-a-64-95-ar-p33",
  "cycle-10/working/c10-066-multilingual-text-un-a-64-95-ar-p34",
  "cycle-10/working/c10-067-multilingual-text-un-a-64-95-ar-p35"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "un-a-64-95-ar",
  caseIds
});
