// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-079-multilingual-text-un-a-64-95-zh-p1",
  "cycle-10/working/c10-080-multilingual-text-un-a-64-95-zh-p2",
  "cycle-10/working/c10-081-multilingual-text-un-a-64-95-zh-p3",
  "cycle-10/working/c10-082-multilingual-text-un-a-64-95-zh-p4",
  "cycle-10/working/c10-083-multilingual-text-un-a-64-95-zh-p5",
  "cycle-10/working/c10-084-multilingual-text-un-a-64-95-zh-p6"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "un-a-64-95-zh",
  caseIds
});
