// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/working/c10-085-text-geometry-uspto-patent-10000000-p12",
  "cycle-10/working/c10-086-text-geometry-uspto-patent-10000000-p13"
];

defineCycleParityShard({
  cycle: 10,
  phase: "working",
  shard: "uspto-patent-10000000",
  caseIds
});
