// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/holdout/c10-117-scientific-technical-arxiv-docling-2408-09869-p1",
  "cycle-10/holdout/c10-118-scientific-technical-arxiv-docling-2408-09869-p2",
  "cycle-10/holdout/c10-119-scientific-technical-arxiv-docling-2408-09869-p3",
  "cycle-10/holdout/c10-120-scientific-technical-arxiv-docling-2408-09869-p4"
];

defineCycleParityShard({
  cycle: 10,
  phase: "holdout",
  shard: "arxiv-docling-2408-09869",
  caseIds
});
