// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/holdout/c10-101-financial-report-boeing-2024-ar-p74",
  "cycle-10/holdout/c10-102-financial-report-boeing-2024-ar-p79",
  "cycle-10/holdout/c10-103-financial-report-boeing-2024-ar-p83",
  "cycle-10/holdout/c10-104-financial-report-boeing-2024-ar-p88",
  "cycle-10/holdout/c10-105-financial-report-boeing-2024-ar-p92",
  "cycle-10/holdout/c10-106-financial-report-boeing-2024-ar-p97",
  "cycle-10/holdout/c10-107-financial-report-boeing-2024-ar-p102",
  "cycle-10/holdout/c10-108-financial-report-boeing-2024-ar-p106",
  "cycle-10/holdout/c10-109-financial-report-boeing-2024-ar-p111",
  "cycle-10/holdout/c10-110-financial-report-boeing-2024-ar-p115"
];

defineCycleParityShard({
  cycle: 10,
  phase: "holdout",
  shard: "boeing-2024-ar",
  caseIds
});
