// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/holdout/c10-111-financial-report-caterpillar-2024-ar-p26",
  "cycle-10/holdout/c10-112-financial-report-caterpillar-2024-ar-p30",
  "cycle-10/holdout/c10-113-financial-report-caterpillar-2024-ar-p33",
  "cycle-10/holdout/c10-114-financial-report-caterpillar-2024-ar-p36",
  "cycle-10/holdout/c10-115-financial-report-caterpillar-2024-ar-p39",
  "cycle-10/holdout/c10-116-financial-report-caterpillar-2024-ar-p42",
  "cycle-10/holdout/c10-117-financial-report-caterpillar-2024-ar-p45",
  "cycle-10/holdout/c10-118-financial-report-caterpillar-2024-ar-p49",
  "cycle-10/holdout/c10-119-financial-report-caterpillar-2024-ar-p52",
  "cycle-10/holdout/c10-120-financial-report-caterpillar-2024-ar-p55"
];

defineCycleParityShard({
  cycle: 10,
  phase: "holdout",
  shard: "caterpillar-2024-ar",
  caseIds
});
