// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/holdout/c10-101-financial-report-federal-reserve-2024-ar-p1",
  "cycle-10/holdout/c10-102-financial-report-federal-reserve-2024-ar-p2",
  "cycle-10/holdout/c10-103-financial-report-federal-reserve-2024-ar-p3",
  "cycle-10/holdout/c10-104-financial-report-federal-reserve-2024-ar-p7"
];

defineCycleParityShard({
  cycle: 10,
  phase: "holdout",
  shard: "federal-reserve-2024-ar",
  caseIds
});
