// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/holdout/c10-109-legal-regulatory-scotus-23-175-p1",
  "cycle-10/holdout/c10-110-legal-regulatory-scotus-23-175-p2",
  "cycle-10/holdout/c10-111-legal-regulatory-scotus-23-175-p3",
  "cycle-10/holdout/c10-112-legal-regulatory-scotus-23-175-p5"
];

defineCycleParityShard({
  cycle: 10,
  phase: "holdout",
  shard: "scotus-23-175",
  caseIds
});
