// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/holdout/c10-113-multilingual-text-un-a-64-95-ru-p1",
  "cycle-10/holdout/c10-114-multilingual-text-un-a-64-95-ru-p2",
  "cycle-10/holdout/c10-115-multilingual-text-un-a-64-95-ru-p3",
  "cycle-10/holdout/c10-116-multilingual-text-un-a-64-95-ru-p4"
];

defineCycleParityShard({
  cycle: 10,
  phase: "holdout",
  shard: "un-a-64-95-ru",
  caseIds
});
