// Generated by scripts/generate-parity-test-shards.mjs. Do not edit by hand.
import { defineCycleParityShard } from "../../../cycle-shard-runner.js";

const caseIds = [
  "cycle-10/holdout/c10-105-forms-annotations-va-21-526ez-p1",
  "cycle-10/holdout/c10-106-forms-annotations-va-21-526ez-p2",
  "cycle-10/holdout/c10-107-forms-annotations-va-21-526ez-p3",
  "cycle-10/holdout/c10-108-forms-annotations-va-21-526ez-p4"
];

defineCycleParityShard({
  cycle: 10,
  phase: "holdout",
  shard: "va-21-526ez",
  caseIds
});
